<?php
/**
 * SETUP CONFIG - Tulis config.env yang benar ke server.
 * HAPUS FILE INI SETELAH DIJALANKAN!
 */

// Proteksi sederhana
$SECRET = "apeiron2024setup";
$submitted_secret = $_POST["secret"] ?? "";

$done = false;
$error = "";
$info = [];

if ($_SERVER["REQUEST_METHOD"] === "POST" && isset($_POST["write_config"])) {
    if ($submitted_secret !== $SECRET) {
        $error = "Kode rahasia salah!";
    } else {
        $config_content = <<<ENV
# License Server Environment Configuration
# Auto-generated by setup_config.php

# Environment
ENVIRONMENT=production

# Database Configuration
DB_HOST=localhost
DB_NAME=u364155471_portal
DB_USER=u364155471_portalapeiron
DB_PASS=@PortalApr21
DB_CHARSET=utf8mb4

# Security Keys
API_KEY=355706461b2a103c48b83d4f57b3891a5b25cf89a26f829a3a2b9ddc6b230983
ENCRYPTION_KEY=18e97a4a8cd55dd5e63f61241ca69ea39f8fca2fa58af17aa2671ae35ce19f5c

# CORS Configuration
CORS_ALLOWED_ORIGINS=https://portal-apeiron.web.id,https://server-apeiron.web.id

# Session Configuration
SESSION_NAME=apeiron_license_admin
SESSION_TIMEOUT=3600

# Rate Limiting
RATE_LIMIT_ENABLED=true
RATE_LIMIT_REQUESTS=100
RATE_LIMIT_WINDOW=3600

# Application Settings
APP_NAME=Apeiron License Server
APP_VERSION=2.0.0
TIMEZONE=Asia/Jakarta

# License Defaults
DEFAULT_EXPIRATION_DAYS=365
DEFAULT_ACTIVATION_LIMIT=1
ENV;

        $path = __DIR__ . "/config.env";
        $bytes = file_put_contents($path, $config_content);
        if ($bytes !== false) {
            $done = true;
        } else {
            $error = "Gagal menulis file! Cek permission folder.";
        }
    }
}

// Baca config.env saat ini
$current_env = [];
$env_path = __DIR__ . "/config.env";
if (file_exists($env_path)) {
    foreach (file($env_path, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) as $line) {
        if (trim($line)[0] === "#" || strpos($line, "=") === false) continue;
        list($k, $v) = explode("=", $line, 2);
        $current_env[trim($k)] = trim($v);
    }
}

// Test DB connection
$db_ok = false;
$db_error = "";
try {
    $dsn = "mysql:host=localhost;dbname=u364155471_portal;charset=utf8mb4";
    $db = new PDO($dsn, "u364155471_portalapeiron", "@PortalApr21", [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
    $db_ok = true;
} catch (PDOException $e) {
    $db_error = $e->getMessage();
}

// Test DB dengan config.env saat ini
$db_env_ok = false;
$db_env_error = "";
if (!empty($current_env["DB_NAME"])) {
    try {
        $dsn2 = "mysql:host=" . ($current_env["DB_HOST"] ?? "localhost") . ";dbname=" . $current_env["DB_NAME"] . ";charset=utf8mb4";
        $db2 = new PDO($dsn2, $current_env["DB_USER"] ?? "", $current_env["DB_PASS"] ?? "", [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        $db_env_ok = true;
    } catch (PDOException $e) {
        $db_env_error = $e->getMessage();
    }
}
?>
<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<title>Setup Config - Portal Apeiron</title>
<style>
body{font-family:monospace;background:#0a0a0f;color:#e0e0e0;padding:30px;max-width:850px;margin:auto}
h2{color:#00d4aa;border-bottom:1px solid #333;padding-bottom:8px;margin-top:0}
.ok{color:#00d4aa;font-weight:bold}.err{color:#ff4757;font-weight:bold}.warn{color:#ffa502;font-weight:bold}
.box{background:#111;border:1px solid #333;border-radius:8px;padding:20px;margin-bottom:20px}
table{border-collapse:collapse;width:100%}
td,th{border:1px solid #333;padding:8px 12px;text-align:left;font-size:13px}
th{background:#1a1a2e;color:#00d4aa}
input[type=text],input[type=password]{background:#1a1a2e;border:1px solid #555;color:#fff;padding:8px 12px;border-radius:5px;width:220px}
button{background:#00d4aa;color:#000;border:none;padding:10px 22px;border-radius:5px;cursor:pointer;font-weight:bold}
.warn-box{background:#2d1a00;border:1px solid #ffa502;border-radius:8px;padding:16px;margin-bottom:20px}
.danger-box{background:#1a0000;border:1px solid #ff4757;border-radius:8px;padding:16px;margin-bottom:20px}
.success-box{background:#0d2d1a;border:1px solid #00d4aa;border-radius:8px;padding:16px;margin-bottom:20px}
</style>
</head>
<body>
<div class="warn-box">
    <b>PERINGATAN:</b> Hapus file <code>setup_config.php</code> dari server setelah selesai!
</div>
<h2>Setup Config.env — Portal Apeiron</h2>

<?php if ($done): ?>
<div class="success-box">
    <b>✅ config.env berhasil ditulis!</b><br><br>
    Sekarang kamu bisa login dengan:<br>
    • Email: <b>admin@portal.com</b><br>
    • Username: <b>admin</b><br>
    • Password: <b>password123</b><br><br>
    <a href="/auth/login.php" style="color:#00d4aa;">→ Ke Halaman Login</a><br><br>
    <b style="color:#ff4757;">Setelah login berhasil, HAPUS file ini dari server!</b>
</div>
<?php elseif ($error): ?>
<div class="danger-box"><b>❌ <?= htmlspecialchars($error) ?></b></div>
<?php endif; ?>

<div class="box">
    <h2>1. Status Koneksi Database</h2>
    <table>
        <tr>
            <th>Sumber Kredensial</th>
            <th>DB Host / Name / User</th>
            <th>Status</th>
        </tr>
        <tr>
            <td><b>Kredensial Benar</b><br><small>(hardcoded)</small></td>
            <td>localhost / u364155471_portal / u364155471_portalapeiron</td>
            <td><?= $db_ok ? "<span class='ok'>✅ BERHASIL</span>" : "<span class='err'>❌ GAGAL: " . htmlspecialchars($db_error) . "</span>" ?></td>
        </tr>
        <tr>
            <td><b>Dari config.env server</b><br><small>(yang aktif sekarang)</small></td>
            <td>
                <?= htmlspecialchars($current_env["DB_HOST"] ?? "-") ?> /
                <?= htmlspecialchars($current_env["DB_NAME"] ?? "-") ?> /
                <?= htmlspecialchars($current_env["DB_USER"] ?? "-") ?>
            </td>
            <td>
                <?php if (empty($current_env["DB_NAME"])): ?>
                    <span class="warn">⚠️ config.env tidak ada/kosong</span>
                <?php elseif ($db_env_ok): ?>
                    <span class="ok">✅ BERHASIL</span>
                <?php else: ?>
                    <span class="err">❌ GAGAL: <?= htmlspecialchars($db_env_error) ?></span>
                <?php endif; ?>
            </td>
        </tr>
    </table>

    <?php if (!$db_env_ok && !empty($current_env["DB_NAME"])): ?>
    <br><span class="err">❌ Ini penyebab login gagal! config.env di server berisi kredensial DB yang salah.</span>
    <br>Gunakan form di bawah untuk memperbaikinya.
    <?php endif; ?>
</div>

<div class="box">
    <h2>2. Isi config.env di Server Saat Ini</h2>
    <?php if (empty($current_env)): ?>
        <span class="warn">⚠️ config.env tidak ada atau kosong di server.</span>
    <?php else: ?>
        <table>
            <thead><tr><th>Key</th><th>Value</th><th>Status</th></tr></thead>
            <tbody>
            <?php
            $expected = [
                "DB_NAME" => "u364155471_portal",
                "DB_USER" => "u364155471_portalapeiron",
                "DB_HOST" => "localhost",
            ];
            foreach ($current_env as $k => $v):
                $display_v = in_array($k, ["DB_PASS","API_KEY","ENCRYPTION_KEY"])
                    ? (empty($v) ? "<span class='err'>KOSONG!</span>" : "<span class='ok'>**** (ada)</span>")
                    : "<code>" . htmlspecialchars($v) . "</code>";
                $status = "";
                if (isset($expected[$k])) {
                    if ($v === $expected[$k]) $status = "<span class='ok'>✅ Benar</span>";
                    else $status = "<span class='err'>❌ Salah! Harusnya: " . htmlspecialchars($expected[$k]) . "</span>";
                }
            ?>
            <tr>
                <td><b><?= htmlspecialchars($k) ?></b></td>
                <td><?= $display_v ?></td>
                <td><?= $status ?></td>
            </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<div class="box">
    <h2>3. Tulis Ulang config.env yang Benar</h2>
    <p>Masukkan kode rahasia untuk menulis ulang config.env dengan kredensial yang benar:</p>
    <form method="POST">
        <table style="width:auto;margin-bottom:14px">
            <tr>
                <td><b>Kode Rahasia:</b></td>
                <td><input type="password" name="secret" placeholder="Masukkan kode rahasia" required></td>
            </tr>
        </table>
        <small style="color:#888;display:block;margin-bottom:12px">Kode rahasia: <b>apeiron2024setup</b></small>
        <button type="submit" name="write_config">✍️ Tulis config.env Sekarang</button>
    </form>
    <br>
    <details>
        <summary style="cursor:pointer;color:#888;">Lihat isi config.env yang akan ditulis...</summary>
        <pre style="background:#0a0a0f;padding:12px;border-radius:6px;margin-top:8px;font-size:12px;color:#aaa">
ENVIRONMENT=production
DB_HOST=localhost
DB_NAME=u364155471_portal
DB_USER=u364155471_portalapeiron
DB_PASS=@PortalApr21
API_KEY=355706461b2a103c48b83d4f57b3891a5b25cf89a26f829a3a2b9ddc6b230983
ENCRYPTION_KEY=18e97a4a8cd55dd5e63f61241ca69ea39f8fca2fa58af17aa2671ae35ce19f5c
CORS_ALLOWED_ORIGINS=https://portal-apeiron.web.id,https://server-apeiron.web.id
SESSION_NAME=apeiron_license_admin
SESSION_TIMEOUT=3600
...</pre>
    </details>
</div>

<div class="box" style="border-color:#ff4757">
    <h2>⚠️ HAPUS FILE INI SETELAH SELESAI!</h2>
    <p>Hapus <code>setup_config.php</code> dari server segera setelah config.env berhasil ditulis!</p>
</div>

</body>
</html>
